### ISSUE TITLE
Assignment 7 numbers wrong printing

### ISSUE THREAD

**Issue by 5bit23** [vtcbca/basic-programming-5bit23#2]
in assignment 7 number is printing in reverse order.

**Comment by 78bit23** [comment]
what is your initial value of loop?

**Comment by 78bit23** [comment]
the initial value is n

**Comment by 5bit23** [comment]
it is n

**Comment by 78bit23** [comment]
what is meaning of n?

**Comment by 5bit23** [comment]
n means number of lines

**Comment by 78bit23** [comment]
you need to start loop with 1 and end with n

**Comment by 5bit23** [comment]
i started with the 1 and now i am printing negative numbers

**Comment by 78bit23** [comment]
change condition also

**Comment by 5bit23** [comment]
ohh i am so stupid

**Comment by 78bit23** [comment]
lol

**Comment by 5bit23** [comment]
thanks now i am getting the right out put

**Comment by 78bit23** [comment]
your welcome!!
